apiVersion: v1
kind: Pod
metadata:
  name: secrets-env
spec:
  containers:
  - name: secrets-env
    image: busybox
    command: ["env"]
    env:
    - name: ADMIN_USER
      valueFrom:
        secretKeyRef:
          name: admin
          key: admin-user
    - name: DEV_USER
      valueFrom:
        secretKeyRef:
          name: dev
          key: dev-user
  restartPolicy: Never
