apiVersion: v1
kind: Pod
metadata:
  name: secret-pod-volume
spec:
  containers:
    - name: demo2
      image: nginx
      volumeMounts:
        - name: vol-secret
          mountPath: /etc/vol-secret
  restartPolicy: Never
  volumes:
    - name: vol-secret
      secret:
        secretName: demo
