apiVersion: v1
kind: Pod
metadata:
  name: task-pv-pod
spec:
  volumes:
    - name: pv-vol
      persistentVolumeClaim:
        claimName: demo-pvclaim
  #nodeName: kubeadm3.19
  containers:  
    - name: pv-pod
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: pv-vol

