
apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
spec:
  containers:
  - image: alpine
    name: emptydir-container
    command: ['sh', '-c', 'sleep 3000']
    volumeMounts:
    - mountPath: /demo
      name: test-vol
  volumes:
  - name: test-vol
    emptyDir: {}
