
apiVersion: v1
kind: Pod
metadata:
  name: hostpath-pod
spec:
  containers:
  - image: alpine
    name: hostpath-container
    command: ['sh', '-c', 'sleep 3000']
    volumeMounts:
    - mountPath: /demo
      name: hp-volume
  volumes:
  - name: hp-volume
    hostPath:
      path: /data
      type: DirectoryOrCreate

