apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: demo
  name: demo
spec:
  containers:
  - image: busybox
    name: demo
    command: [ "/bin/sh", "-c", "env"]
    env:
        - name: HELLO
          valueFrom:
            configMapKeyRef:
              name: demo
              key: name
  restartPolicy: Never
status: {}
